# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6ca9c8ef6759e41ca38ca3ec6bf191c92a955705e8bbfcf5db1a703fc0fb626a0d67bc061332d636a58d3152673efb83af5f881685e4430b869cee8d4892d8e

test:
  secret_key_base: e64cc336e3eec1e2ea40ee30256cd17832ceefcb995c0707182d308763a7acd8f8849ca4d3f9041262739c6d0909631f4af212815e54d0ccafb193def62ca13a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
